from tkinter import *
from tkinter import messagebox
global Key,Path
def DOE():
    file = open(path.get(), 'rb')
    f = file.read()
    file.close()
    f = bytearray(f)
    for index, values in enumerate(f):
        f[index] = values ^ key.get()
    file = open(path.get(), 'wb')
    file.write(f)
    file.close()
    encrypt_file.config(state=DISABLED)
    decrypt_file.config(state=NORMAL)
    messagebox.showinfo("Information", "Encryption Completed")
    main.pack()
    EF.pack_forget()
def Encrypt():
    main.pack_forget()
    global path,key,EF
    path=StringVar()
    key=IntVar()
    EF=Frame()
    EF.pack()
    Label(EF,text="Enter Location : ").pack()
    Entry(EF,textvariable=path).pack()
    Label(EF,text="Enter Password : ").pack()
    Entry(EF,textvariable=key).pack()
    Button(EF,image=SP,command=DOE).pack()
def DOD():
    file = open(path.get(), 'rb')
    f = file.read()
    file.close()
    f = bytearray(f)
    for index, values in enumerate(f):
        f[index] = values ^ key.get()
    file = open(path.get(), 'wb')
    file.write(f)
    file.close()
    encrypt_file.config(state=NORMAL)
    decrypt_file.config(state=DISABLED)
    messagebox.showinfo("Information" , "Decryption Completed")
def Decrypt():
    main.pack_forget()
    global path,key
    path=StringVar()
    key=IntVar()
    Label(text="Enter Location : ").pack()
    Entry(textvariable=path).pack()
    Label(text="Enter Password : ").pack()
    Entry(textvariable=key).pack()
    Button(image=SP,command=DOD).pack()
Pranjal = Tk()
Pranjal.geometry("900x400")
Pranjal.resizable(0,0)
E=PhotoImage(file=r"C:\Users\student\Downloads\e.png")
D=PhotoImage(file=r"C:\Users\student\Downloads\d.png")
SP=PhotoImage(file=r"C:\Users\student\Downloads\sp.png")
BG=PhotoImage(file=r"C:\Users\student\Downloads\bg.png")
Label(image=BG).place(x=0,y=0)
main=Frame(bg="grey20")
encrypt_file = Button(main,image=E,borderwidth=0,command=Encrypt,bg="grey20")
encrypt_file.pack()
decrypt_file = Button(main,image=D,borderwidth=0,command=Decrypt,bg="grey20")
decrypt_file.pack()
decrypt_file.config(state=DISABLED)
main.pack()
Pranjal.mainloop()
